# Dockerfile generated by DevOpsArk

# Use the official Node.js LTS image as the base image
FROM node:lts

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package definition files first for layer caching
COPY package*.json ./

# Install dependencies as specified in package-lock.json/package.json
RUN npm ci --only=production

# Copy the rest of the application source code
COPY . .

# Expose application port (commonly 3000 for Node.js; adjust as needed)
EXPOSE 3000

# Set the default command to run the application
CMD ["node", "index.js"]